version: '3.8'

services:
  api:
    build: ./project
    # Auto-reload enabled. Only one worker.
    command: uvicorn app.app_main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      # Mount the code into the container. This avoid to re-build the image after a code change.
      - ./project:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - PYTHONPATH=/usr/src/app/
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/historical_figures_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/historical_figures_test
    depends_on:
      - db
  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres